language: php
php:
  - 5.6
cache:
  directories:
    - $HOME/.cache/bower
    - $HOME/.composer/cache
    - $TRAVIS_BUILD_DIR/node_modules
branches:
  only:
    - 8.x-1.x
before_install:
  # Disable debugging
  - phpenv config-rm xdebug.ini
  # Update Node.js (if too old)
  - nvm install 6.2.2
  - nvm use 6.2.2
install:
  - npm install
before_script:
  - php --version
  - node --version
  - npm --version
script: 'npm test && npm run compile'
notifications:
  email:
    on_success: never
    on_failure: always
